name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # build at least once a month
    - cron: '0 0 1 * *'

jobs:
  appimage-x86_64:
    name: AppImage x86_64
    runs-on: ubuntu-18.04
    env:
      ARCH: x86_64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build AppImage
        run: bash -ex ci/build-appimage.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage x86_64
          path: linuxdeploy-plugin-appimage*.AppImage*

  appimage-i386:
    name: AppImage i386
    runs-on: ubuntu-18.04
    env:
      ARCH: i386
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install -y g++-multilib libc6-dev:i386 libstdc++-5-dev:i386 zlib1g:i386 libfuse2:i386
      - name: Build AppImage
        run: bash -ex ci/build-appimage.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage i386
          path: linuxdeploy-plugin-appimage*.AppImage*
      - name: Upload release asset
        if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: linuxdeploy-plugin-appimage*.AppImage*

  upload:
    name: Create release and upload artifacts
    needs:
      - appimage-x86_64
      - appimage-i386
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/linuxdeploy-plugin-appimage*.AppImage*
